version: '3'

services:
  mysql:
    image: mariadb:latest
    container_name: api_mysql
    volumes:
      - api_db_data:/var/lib/mysql
    restart: always
    networks:
      - api_net
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - api_net

networks:
  api_net:
    driver: 'bridge'

volumes:
  api_db_data:
