create table auth_user
(
    id                 bigint generated by default as identity primary key,
    created_at         timestamp    not null,
    updated_at         timestamp,
    uuid               varchar(255) not null constraint public_id_user unique,
    email              varchar(255) not null,
    first_name         varchar(255) not null,
    infos              varchar(10000),
    last_login_at      timestamp,
    last_name          varchar(255) not null,
    password           varchar(255) not null,
    user_role          varchar(255) not null,
    hospital_room_uuid varchar(255),
    username           varchar(255) not null constraint username_user_unique unique
);

create table file_entity
(
    id         bigint generated by default as identity primary key,
    created_at timestamp    not null,
    updated_at timestamp,
    uuid       varchar(255) not null constraint public_id_file unique,
    file_name  varchar(255) not null,
    file_path  varchar(255) not null,
    file_size  bigint       not null,
    file_owner bigint       not null constraint link_file_user references auth_user
);

create table alert_entity
(
    id         bigint generated by default as identity primary key,
    created_at timestamp    not null,
    updated_at timestamp,
    uuid       varchar(255) not null constraint public_id_alert unique,
    importance varchar(255) not null,
    infos      varchar(10000),
    status     varchar(255) not null,
    type       varchar(255) not null,
    patient_id bigint       not null constraint link_patient_alert references auth_user,
    staff_id   bigint constraint link_staff_alert references auth_user
);

create table hospital
(
    id         bigint generated by default as identity primary key,
    created_at timestamp    not null,
    updated_at timestamp,
    uuid       varchar(255) not null constraint public_id_hospital unique,
    address    varchar(255) not null,
    name       varchar(255) not null
);

create table service
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp    not null,
    updated_at  timestamp,
    uuid        varchar(255) not null constraint public_id_service unique,
    name        varchar(255) not null,
    hospital_id bigint       not null constraint link_hospital_service references hospital
);

create table room
(
    id         bigint generated by default as identity primary key,
    created_at timestamp    not null,
    updated_at timestamp,
    uuid       varchar(255) not null constraint public_id_room unique,
    name       varchar(255) not null,
    service_id bigint       not null constraint link_room_service references service
);

create table log_action
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp    not null,
    updated_at  timestamp,
    uuid        varchar(255) not null constraint public_id_log unique,
    http_method varchar(255) not null,
    ip          varchar(255) not null,
    route       varchar(255) not null,
    user_uuid   varchar(255),
    when_access timestamp    not null
);

create table user_password_reset_codes
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp    not null,
    updated_at      timestamp,
    uuid            varchar(255) not null constraint public_id_user_password_reset unique,
    code            varchar(1000),
    expiration_date timestamp    not null,
    user_id         bigint       not null constraint link_password_to_user references auth_user
);

create table user_tokens
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp     not null,
    updated_at      timestamp,
    uuid            varchar(255)  not null constraint public_id_user_tokens unique,
    expiration_date timestamp     not null,
    token           varchar(2000) not null constraint token_unique_user unique,
    user_id         bigint        not null constraint token_link_user references auth_user
);
