version: '3.7'

services:
  auth:
    build:
      context: ../../services/auth
    container_name: hospyboard_auth
    hostname: hb_auth
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 9090:9090

networks:
  default:
    name: hospyboard_network