version: '3.7'

services:
  user:
    build:
      context: ../../services/user
    container_name: hospyboard_user
    hostname: hb_user
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 9090:9090

networks:
  default:
    name: hospyboard_network