version: '3.7'

services:
  mysql:
    image: mariadb:latest
    container_name: hospyboard_db
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default
    ports:
      - "3306:3306"

  hospyboard:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: hospyboard_api
    hostname: hospyboard_api
    depends_on:
      - mysql
    networks:
      - default
    restart: on-failure
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "9090:9090"

  mail:
    image: maildev/maildev
    container_name: hospyboard_api_mail
    networks:
      - default
    restart: on-failure
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  default:
    name: hospyboard_network
    driver: bridge
