version: '3.9'

services:
  mysql:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - hospyboard_api_db:/var/lib/mysql
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "3387:5432"

  hospyboard:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: hospyboard_api
    hostname: hospyboard_api
    depends_on:
      - mysql
    networks:
      - default
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "9097:9090"

  mail:
    image: maildev/maildev
    container_name: hospyboard_api_mail
    networks:
      - default
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  default:
    name: hospyboard_network
    driver: bridge

volumes:
  hospyboard_api_db:
