create table auth_user
(
    id         bigint generated by default as identity constraint auth_user_pkey primary key,
    uuid       varchar(255) not null constraint uuid_unique_key unique,
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    password   varchar(255) not null,
    user_role  varchar(255) not null
);

create table alert_entity
(
    id           bigint generated by default as identity constraint alert_entity_pkey primary key,
    alert_uuid   varchar(255) not null constraint alert_uuid_unique_key unique,
    importance   varchar(255) not null,
    patient_uuid varchar(255) not null,
    staff_uuid   varchar(255),
    status       varchar(255) not null,
    type         varchar(255) not null
);

create table hospital_room
(
    id          bigint generated by default as identity constraint hospital_room_pkey primary key,
    uuid        varchar(255) not null constraint room_unique_key unique,
    room_number varchar(255)
);

create table hospital_room_tool
(
    id        bigint generated by default as identity constraint hospital_room_tool_pkey primary key,
    uuid      varchar(255) not null constraint room_tool_unique_key unique,
    tool_type varchar(255)
);

create table hospyboard_action
(
    id           bigint generated by default as identity constraint hospyboard_action_pkey primary key,
    requested_at varchar(255),
    route_name   varchar(255),
    service      varchar(255),
    user_uuid    varchar(255),
    uuid         varchar(255) not null constraint action_unique_key unique
);
